"""create analyses table

Revision ID: 0ead5501aaa0
Revises: 52e66c5a971f
Create Date: 2026-05-21 00:35:44.873490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ead5501aaa0'
down_revision: Union[str, Sequence[str], None] = '52e66c5a971f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('github_profile_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('missing_skills', sa.Text(), nullable=False),
    sa.Column('internship_email', sa.Text(), nullable=False),
    sa.Column('linkedin_message', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['cvs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['github_profile_id'], ['github_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    # ### end Alembic commands ###
